# Site settings
name: Ivan M. Munyengeterwa
email: ivanmunyengeterwa37@gmail.com
#canonical_url: https://portfolio.com
keywords: "Software Engineer, Python, Java, Machine Learning, Deep Learning, Web-design, Algorithms"
skills: "Middle-level Software Engineer in Harare, Zimbabwe (Bsc Computer Science. msu)"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ivanmunyengeterwa/
 
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
